### ISSUE TITLE
AIS_Line Points() method doesn't make expected changes to parameters

### ISSUE THREAD

**Issue by shrdluk** [LaughlinResearch/pyOCCT#10]
## Expected Behavior

I'm trying to retrieve the end points of an `AIS_Line` instance. 

The [OCCT documentation for AIS_Line](https://www.opencascade.com/doc/occt-7.2.0/refman/html/class_a_i_s___line.html) gives the `Points()` method:
> void Points (Handle< Geom_Point > &thePStart, Handle< Geom_Point > &thePEnd) const
>  Returns the starting point thePStart and the end point thePEnd of the line set by SetPoints.

## Current Behavior

In pyOCCT, `Geom_Point` instances passed to the method are unchanged. See test program below.

Other parts of `AIS_Line`, including `SetPoints()` seem to work fine.

## Possible Solution

I can't see any obvious problems in AIS.cpp. I've used lots of similar methods without issues. Wild guess - the parameters are specified as `Geom_Point`, but that class doesn't have a constructor so I'm using `Geom_CartesianPoint`. Something to do with upcasting/downcasting?

## Steps to Reproduce (for bugs)

Short test program:
```
from OCCT.gp import gp_Pnt
from OCCT.AIS import AIS_Line
from OCCT.Geom import Geom_CartesianPoint

# Construct points for line
pt1 = Geom_CartesianPoint(10.0, 20.0, 30.0)
pt2 = Geom_CartesianPoint(40.0, 50.0, 60.0)
print("Pts set:", pt1.Coord(0.0, 0.0, 0.0), pt2.Coord(0.0, 0.0, 0.0))

# Construct the line
line = AIS_Line(pt1, pt2)
line.SetPoints(pt1, pt2)  # Get same result without this line, but just to confirm

# Point instances for Points() method
pt3 = Geom_CartesianPoint(gp_Pnt())
pt4 = Geom_CartesianPoint(gp_Pnt())

# Invoke the Points() method
line.Points(pt3, pt4)
print("Pts retrieved 1:", pt3.Coord(0.0, 0.0, 0.0), pt4.Coord(0.0, 0.0, 0.0))

# Initialise points to non-zero values
pt5 = Geom_CartesianPoint(7.0, 8.0, 9.0)
pt6 = Geom_CartesianPoint(7.5, 8.5, 9.5)

# Invoke the Points() method
line.Points(pt5, pt6)
print("Pts retrieved 2:", pt5.Coord(0.0, 0.0, 0.0), pt6.Coord(0.0, 0.0, 0.0))
```
Results:
```
Pts set: (10.0, 20.0, 30.0) (40.0, 50.0, 60.0)
Pts retrieved 1: (0.0, 0.0, 0.0) (0.0, 0.0, 0.0)
Pts retrieved 2: (7.0, 8.0, 9.0) (7.5, 8.5, 9.5)
```
## Context

I can easily work round this. I'm raising it because it may be an indicator of related issues elsewhere.

## Your Environment

* Version used: Current
* Operating System and version (desktop or mobile): Linux
* Link to your project:

## OpenCASCADE Bug

It's possible that it's a bug in the OCCT code, but AIS_Line.hxx in occt-7.2.0-2  has the following implementation, which looks OK to me:
```
//! Returns the starting point thePStart and the end point thePEnd of the line set by SetPoints.
  void Points (Handle(Geom_Point)& thePStart, Handle(Geom_Point)& thePEnd) const
  {
    thePStart = myStartPoint;
    thePEnd   = myEndPoint;
  }
```

**Comment by trelau** [comment]
Thanks for reporting the issue. I think this is due to the fact that the variables are changed in place with the "=" sign. This is fine it C++ but this doesn't get picked up by Python. Maybe there is an option to adjust pybind11 return value policies, but I usually get around this by writing the method as a lambda. See this commit for reference: https://github.com/LaughlinResearch/pyOCCT/commit/6f37aa3d23bd37fa87237a9be494d4cfbf6cfd02

I still require dummy arguments to maintain the same function signature, but now the values are also returned along with the regular outputs in a tuple. I've had to fix these on a case-by-case basis.

My only idea for more permanently fixing this issue (and others that haven't been identified yet) is to actually parse the C++ source instead of just the header when generating the bindings. Then, search for the source code for types that are "non const" to see if they get re-assigned with "=". If so, automatically write the function as a lambda. This is a theory, and be a much heavier task than just parsing headers, so other ideas or welcomed.

I think a similar "fix" to the referenced commit will be what you need. I can't implement the fix right now, but can in the next few days.

**Comment by trelau** [comment]
I've implemented a fix in this commit: https://github.com/LaughlinResearch/pyOCCT/commit/5b73d412dcb45e34bf8d60c8279a598e5ea8ad52

I'll ask pybind11 gitter for any better ways. I can implement a feature in the binding generator that will write as shown in the commit, but you'll still have to specify what functions to apply this to manually. Since this is a known issue and there is a straightforward fix, perhaps users can fix on a case-by-case basis and create unit tests and submit their own PR's. I'll be sure to add it to the documentation.

**Comment by shrdluk** [comment]
The issue seems to arise when the method assigns a new value (pointing to an internal structure) to the argument passed into it, instead of copying fields into the reference it's been given. This works fine in C++, where it is treated as a pointer, but not in Python unless steps are taken to return this new value via the lambda/tuple technique.

I wondered if this situation is common in pyOCCT, so I wrote a little Python program to go through all the OCCT .hxx files looking for the pattern "theX = myY". It flagged up about 30 occurrences in all. I checked all of these and didn't see anything that I thought would cause problems. Many of them involve Standard_Real parameters, and already have lambdas in place.

Of course this assumes that the OCCT codebase is consistent in its use of the/my naming, and that the implementation of these functions are all in the .hxx files rather than elsewhere. Nevertheless, it means we can be reasonably confident that AIS_Line was a one-off and not a symptom of a more widespread issue.

**Comment by trelau** [comment]
Cool. I can add a check in the binder to look for “non const” types passed by reference and see if they get assigned in the header files. This is what I already do for immutable types like Standard_Real, but could extend it for any type and to look for “=“. There are cases where things are assigned in the cxx files. I think the best approach will be the ability to specify them in the binder configuration file, and just build up the cases as people use it, making unit tests along the way to verify they are captured in following iterations.

**Comment by shrdluk** [comment]
I don't know if it helps, but my check flagged `Select3D_SensitiveTriangle::Points3D()` as a potential problem. This looks very similar to `AIS_Line::Points()` but it works fine (see below). The immediately apparent differences are:
- `Select3D_SensitiveTriangle::Points3D()` parameters are `gp_Pnt` instead of `Handle(Geom_Point)`
- `Select3D_SensitiveTriangle::Points3D()` assignments are from elements of an array, rather than a complete object, ie `thePnt0 = myPoints[0]`, not `thePStart = myStartPoint`

I wonder if the additional indirection of a `Handle` makes it more difficult for pybind11 to do the Right Thing.

Test program for `Select3D_SensitiveTriangle::Points3D()`:
```
from OCCT.gp import gp_Pnt
from OCCT.Select3D import Select3D_SensitiveTriangle

# Construct points
pt0 = gp_Pnt(1.0, 2.0, 3.0)
pt1 = gp_Pnt(4.0, 5.0, 6.0)
pt2 = gp_Pnt(7.0, 8.0, 9.0)
print("Pts set:", pt0.Coord(0.0, 0.0, 0.0), pt1.Coord(0.0, 0.0, 0.0),
                                                 pt2.Coord(0.0, 0.0, 0.0))

# Construct the triangle
tri = Select3D_SensitiveTriangle(None, pt0, pt1, pt2)

pt3 = gp_Pnt()
pt4 = gp_Pnt()
pt5 = gp_Pnt()

tri.Points3D(pt3, pt4, pt5)
print("Pts retrieved:", pt3.Coord(0.0, 0.0, 0.0), pt4.Coord(0.0, 0.0, 0.0),
                                                 pt5.Coord(0.0, 0.0, 0.0))
```
Results:
```
Pts set: (1.0, 2.0, 3.0) (4.0, 5.0, 6.0) (7.0, 8.0, 9.0)
Pts retrieved: (1.0, 2.0, 3.0) (4.0, 5.0, 6.0) (7.0, 8.0, 9.0)
```

**Comment by trelau** [comment]
Interesting, I’ll have to check this out. Someone did give some maybe useful advice on pybind11 gitter: https://gitter.im/pybind/Lobby?at=5afad0efa2d95136333f7956

**Comment by trelau** [comment]
Added a test case for the Select3D case in https://github.com/LaughlinResearch/pyOCCT/commit/c8a49cb7674b05c144ab97487366f0249a7bb9bb

Interesting that it works for `gp_Pnt` point types but not `Geom_CartesianPoint`. I think it has to do with the fact that `gp_Pnt` is wrapped with a `std::unique_ptr` while `Geom_CartesianPoint` uses `opencascade::handle` as the holder type since it is derived from `Standard_Transient`.

I'm going to close this issue for now, but perhaps open a new issue to circle back on to test in more detail.
