### ISSUE TITLE
is ubuntu16.0.4 supported in 7.3.0

### ISSUE THREAD

**Issue by liuxin2322** [LaughlinResearch/pyOCCT#28]
I used to use pythonocc，but I find that it cannot retrieve name of parts in step file by OCAF～   i'm looking forward to know if your repo support the feature?

**Comment by trelau** [comment]
do you have an example file, script, or something to formulate a test with?

**Comment by liuxin2322** [comment]
Dear trelau:
     i'm testing pyOCCT 7.2.0 while some bug occurs.
     operation system :ubuntu16.04
    python:3.5
![image](https://user-images.githubusercontent.com/42459125/66217215-7a9f0d80-e6f9-11e9-807a-d02e6511bef0.png)
    
  could you help me solve the issue?

**Comment by trelau** [comment]
hmmm....that will be tough for me to debug since I only work on windows 😬 

but...there is some logic in the CMake script for XwWindow https://github.com/LaughlinResearch/pyOCCT/blob/master/CMakeLists.txt#L272-L277 i wonder if that has anything to do with it? did Xw_Window get skipped? i guess not or it wouldn't be able to import it...

or maybe an issue here? https://github.com/LaughlinResearch/pyOCCT/blob/master/OCCT/Visualization/Basic.py#L119

**Comment by liuxin2322** [comment]
thanks，i will try it:grinning:

**Comment by frmdstryr** [comment]
If using wayland you need to set `QT_QPA_PLATFORM=xcb`

**Comment by trelau** [comment]
latest master has support for "ubuntu-latest" which i guess is 18.04. If 16.04 support is needed i guess we'll have to add that to the CI matrix?

**Comment by trelau** [comment]
recent work should support ubuntu 16.0.4 and occt 7.4.0
